0.3.0
krixon/domain-event pull request #3
Opened 2019-03-26 14:29 UTC by ben-gibson

2019-03-26 19:25 UTC, ben-gibson commented
It might be good to integrate this repository with a build tool like [travis](https://travis-ci.com) that will include the test results within the PRs etc.

2019-03-27 12:28 UTC, krixon requested changes

2019-03-27 12:28 UTC, krixon commented on tests/Sourcing/EventSteamTest.php
> +class EventSteamTest extends TestCase
Typo in the class name.

```suggestion
class EventStreamTest extends TestCase
```

2019-03-27 12:28 UTC, krixon commented on tests/Sourcing/EventSteamTest.php
> +    public function testRejectsSteamWithNoEvents() : void
```suggestion
    public function testRejectsStreamWithNoEvents() : void
```

2019-03-27 12:28 UTC, krixon commented on tests/Sourcing/EventSteamTest.php
> +        $steamId = new EventStreamId('foo');
```suggestion
        $streamId = new EventStreamId('foo');
```

2019-03-27 12:28 UTC, krixon commented on tests/Sourcing/EventSteamTest.php
> +        $steamId = new EventStreamId('foo');
```suggestion
        $streamId = new EventStreamId('foo');
```

2019-03-27 13:18 UTC, ben-gibson commented on tests/Sourcing/EventSteamTest.php
> +class EventSteamTest extends TestCase
Fixed

2019-03-27 13:19 UTC, ben-gibson commented on tests/Sourcing/EventSteamTest.php
> +    public function testRejectsSteamWithNoEvents() : void
Fixed

2019-03-28 15:20 UTC, krixon submitted a review, later dismissed

2019-03-28 15:30 UTC, krixon approved these changes

2019-03-28 15:32 UTC, merged